spring:
  application:
    name: SBMS-03
  boot:
    admin:
      client:
        url:
        - http://localhost:1111/

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
