spring:
  application:
    name: SBMS-08-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MayurChikane/Configuration-Properties
          username: MayurChikane
          password: mayursakharamchikane
          default-label: main
          clone-on-start: false

server:
 port: 8888
